# Generated by Django 4.2.19 on 2025-03-07 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='task',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
